"""add_avatar_physical_description

Revision ID: b03f987a7a3f
Revises: dd211de0568a
Create Date: 2026-07-14 06:33:09.782660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03f987a7a3f'
down_revision: Union[str, None] = 'dd211de0568a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('physical_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatars', 'physical_description')
    # ### end Alembic commands ###
